name: Full CI/CD Restaurant Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
    # Frontend steps
      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # Backend steps
      - name: Setup Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci
      
        # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


      # Build and push Docker images
      - name: Build and push frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/restaurant-frontend-image1:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/restaurant-frontend-image1:latest


      - name: Build and push backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/restaurant-backend-image1:latest ./backend  
          docker push ${{ secrets.DOCKER_USERNAME }}/restaurant-backend-image1:latest

      # Commented out: Stop and remove containers
      # - name: Stop and remove frontend container
      #   run: |
      #     docker ps -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/restaurant-frontend:latest | xargs -r docker stop
      #     docker ps -a -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/restaurant-frontend:latest | xargs -r docker rm

      # - name: Stop and remove backend container
      #   run: |
      #     docker ps -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/restaurant-backend:latest | xargs -r docker stop
      #     docker ps -a -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/restaurant-backend:latest | xargs -r docker rm
